apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:DsqXywRv55Q/DDXwZ8ZLAXk6oBZZFe27,iv:xEObeQiJH9r+8+atbS47T0NyUbdww3CeWZIoH59KpJs=,tag:9bRxDe4C+A6TtIOoxrcojw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:x3MTW42ACdDivAS3aeVOuCtskWY1pyuxQUMVzL3johsDcxthrQ==,iv:juZCq663CJoWm9iY0t8oT5bIln4mt1BMpnnS1rH25CI=,tag:BGhQwgqsEtfMDz5rAEAVDA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:QTBSBmDm85LHrY71y+o=,iv:pzp95kNxwglvzbRDsD08NYCI/CrTB1kVF+eCnUGNJSI=,tag:A3z3iFTE5ttuxVIoQCyCeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nlv5rtduhdk5wejwnehwew50p9u4fw367sc8stmt9cluuwd68dwsudsr3a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z01GQUhOVG1TWmNzcTZQ
            eE15K3pMV2F4YllQckFlQ2F2anJQR3N4RmcwClI2enNxNEtJU3JsRzdUUXp1bGFF
            bHFxeWpIbml5VEk2c0JnYmJSaDA2UG8KLS0tIEhRWWU1eUNVU21YZ2pKc04vd2VP
            NmFxenB0bTN4TEdFSzBMMVVlcHI2SVEKSeZMaLxCputY4yXNRNCk8qLkm8WL3WIz
            avdFeW6ew+/s+ieOVE+qyoNH7DL5XtGirX7sPNll5ccp96MOLXu0XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-30T20:25:27Z"
    mac: ENC[AES256_GCM,data:3KXOo4Znji9WRDgvs6vD1Ydadob1fj7OlcrnuBhK6v/OWiy6Uto6zTVamVfNEdM6lxOknWj7l4NVqYAxjJFZNcMejbsB/PSkQmFjDMGhWqpteNXTbH8Qf6I/52a8DfvFWqqhLsqfsiTrPQXH6P2MWclMWtTMgJHF9MxRkY6Ibq8=,iv:psOvPTCD22Njhu4anEKs2CgX3lFk4lfrOA8Di//DIVk=,tag:RrhPBroOvC2DxcT0+dBs4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
