---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1nlv5rtduhdk5wejwnehwew50p9u4fw367sc8stmt9cluuwd68dwsudsr3a
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1nlv5rtduhdk5wejwnehwew50p9u4fw367sc8stmt9cluuwd68dwsudsr3a
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1nlv5rtduhdk5wejwnehwew50p9u4fw367sc8stmt9cluuwd68dwsudsr3a
