---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: isinfinder-scraper-python
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/wlwwt/isinfinder-scraper-python
      tag: 0.3.1@sha256:7146b43e46e008f80f266574087ce37fdb479e455d7fee17bd21d500b273207c
    resources:
      requests:
        cpu: 100m
        memory: 128M
      limits:
        memory: 256M
