---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"
  KUBE_VIP_ADDR: "192.168.100.254"
  METALLB_LB_RANGE: "192.168.100.220-192.168.100.240"
  METALLB_K8S_GATEWAY_ADDR: "192.168.100.220"
  METALLB_INGRESS_ADDR: "192.168.100.221"
